Web/HookahCulture.Web/Areas/Administration/Controllers/GalleryController.cs
namespace HookahCulture.Web.Areas.Administration.Controllers
{
    using System.Linq;
    using System.Threading.Tasks;
    using HookahCulture.Data.Models;
    using HookahCulture.Services.Data;
    using HookahCulture.Web.ViewModels.Gallery;
    using Microsoft.AspNetCore.Authorization;
    using Microsoft.AspNetCore.Mvc;

    [Area("Administration")]
    [Authorize(Roles = "Administrator")]
    public class GalleryController : Controller
    {
        private readonly IImagesService imagesService;
        private readonly IPostsService postsService;

        public GalleryController(IImagesService imagesService, IPostsService postsService)
        {
            this.imagesService = imagesService;
            this.postsService = postsService;
        }

        [HttpGet]
        [Authorize(Roles = "Administrator")]
        public async Task<IActionResult> Index()
        {
            var viewModel = new GalleryViewModel();
            var images = this.imagesService.GetAllImagesForAdminApproval<GalleryImageInputViewModel>().ToList();
            var recenytlyRegisteredUsers = this.postsService.GetRecentlyRegisteredUsers();

            viewModel.Images = images;
            viewModel.RecentlyRegisteredUsers = recenytlyRegisteredUsers;

            return this.View(viewModel);
        }

        [HttpPost]
        [Authorize(Roles = "Administrator")]
        public async Task<IActionResult> Approve(int imageId)
        {
            this.imagesService.GetImageForApproval(imageId);

            return this.RedirectToAction("Index");
        }
    }
}

Web/HookahCulture.Web/Controllers/GalleryController.cs
using HookahCulture.Data.Models;
using HookahCulture.Services.Data;
using HookahCulture.Web.ViewModels.Gallery;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;

namespace HookahCulture.Web.Controllers
{
    public class GalleryController : Controller
    {
        private readonly IWebHostEnvironment hostingEnvironment;
        private readonly IUploadsService uploadsService;
        private readonly IImagesService imagesService;
        private readonly UserManager<ApplicationUser> userManager;
        private readonly IPostsService postsService;

        public GalleryController(IWebHostEnvironment hostingEnvironment, IUploadsService uploadsService, IImagesService imagesService, UserManager<ApplicationUser> userManager, IPostsService postsService)
        {
            this.hostingEnvironment = hostingEnvironment;
            this.uploadsService = uploadsService;
            this.imagesService = imagesService;
            this.userManager = userManager;
            this.postsService = postsService;
        }

        [HttpGet]
        [Authorize]
        public async Task<IActionResult> Index()
        {
            var viewModel = new GalleryViewModel();
            var images = this.imagesService.GetAllImages<GalleryImageInputViewModel>().ToList();
            var recenytlyRegisteredUsers = this.postsService.GetRecentlyRegisteredUsers();

            viewModel.Images = images;
            viewModel.RecentlyRegisteredUsers = recenytlyRegisteredUsers;

            return this.View(viewModel);
        }

        [Authorize]
        public async Task<IActionResult> UploadImage(GalleryViewModel model)
        {
            var user = await this.userManager.GetUserAsync(this.User);

            string uniqueFileName = null;

            if (model.ImageUpload != null && this.ModelState.IsValid)
            {
                string uploadsFolder = Path.Combine(hostingEnvironment.WebRootPath, "images/Gallery");
                uniqueFileName = Guid.NewGuid().ToString() + "_" + model.ImageUpload.FileName;
                string filePath = Path.Combine(uploadsFolder, uniqueFileName);
                model.ImageUpload.CopyTo(new FileStream(filePath, FileMode.Create));

                this.uploadsService.UploadImageInGallery(user, uniqueFileName);

                return this.Redirect("/Gallery/Index");
            }
            else
            {
                return this.Redirect("/Gallery/Index");
            }
        }
    }
}

Web/HookahCulture.Web/Views/Gallery/Index.cshtml
@using HookahCulture.Web.ViewModels;
@using HookahCulture.Data.Models;
@inject Microsoft.AspNetCore.Identity.UserManager<ApplicationUser> userManager;
@model HookahCulture.Web.ViewModels.Gallery.GalleryViewModel;

@{ var currentUser = await this.userManager.GetUserAsync(this.User);}

<body>

    <div id="page-contents">
        <div class="container">
            <div class="row">
                <div class="col-md-3 static">
                    <div class="profile-card">
                        <img src="~/images/ProfilePictures/@currentUser.ProfilePicturePath" alt="user" class="profile-photo" />
                        <h5><a href="/Timeline/PersonalTimeLine?timelineId=@currentUser.TimelineId" class="text-white">@currentUser.FirstName @currentUser.LastName</a></h5>
                        <a href="#" class="text-white"></a>
                    </div><!--profile card ends-->
                    <ul class="nav-news-feed">
                        <li><i class="icon ion-ios-paper"></i><div><a href="/Timeline/PersonalTimeline?timelineId=@currentUser.TimelineId">My Newsfeed</a></div></li>
                        <li><i class="icon ion-chatboxes"></i><div><a href="/Chat/Chat">Chat Room</a></div></li>
                        <li><i class="icon ion-images"></i><div><a href="/Gallery/Index">Gallery</a></div></li>
                    </ul><!--news-feed links ends-->
                    <div id="chat-block">
                        <div class="title">Chat online</div>
                        <ul class="online-users list-inline">
                            <div class="alert-info">Recently Registered Users!</div>
                            @foreach (var user in Model.RecentlyRegisteredUsers)
                            {
                                if (user.ProfilePicturePath == null)
                                {
                                    <li><a href="/Timeline/PersonalTimeline?timelineId=@user.TimelineId" title="@user.FirstName @user.LastName"><img src="~/images/ProfilePictures/exampleProfilePicture.png" alt="user" class="img-responsive profile-photo" /><span class="online-dot"></span></a></li>
                                }
                                else
                                {
                                    <li><a href="/Timeline/PersonalTimeline?timelineId=@user.TimelineId" title="@user.FirstName @user.LastName"><img src="~/images/ProfilePictures/@user.ProfilePicturePath" alt="user" class="img-responsive profile-photo" /><span class="online-dot"></span></a></li>
                                }
                            }
                        </ul>
                    </div><!--chat block ends-->
                </div>

                <div class="col-md-7">

                    <!-- Post Create Box
                    ================================================= -->
                    <form enctype="multipart/form-data" class="upload-image" asp-controller="Gallery" asp-action="UploadImage">
                        <div class="row">
                            <div class="col-md-7 col-sm-7">
                            </div>
                            <div class="col-md-5 col-sm-5">
                                <div class="tools">
                                    @*<input asp-for="ImageUpload" />*@
                                </div>
                            </div>
                        </div>
                        <button type="submit" asp-controller="Gallery" asp-action="UploadImage" formmethod="post" class="btn btn-primary pull-right">Upload a picture.<input asp-for="ImageUpload" /></button>
                    </form><!--Post Create Box End-->

                    <div class="alert alert-success" role="alert"> Upload a picture and if it gets approved, it will be posted on our Galley section below!</div>
                    <!-- Media
                    ================================================= -->
                    <div class="media">
                        <div class="row js-masonry" data-masonry='{ "itemSelector": ".grid-item", "columnWidth": ".grid-sizer", "percentPosition": true }'>
                            <div class="grid-sizer col-md-6 col-sm-6"></div>

                            @foreach (var image in Model.Images)
                            {
                                <div class="grid-item col-md-6 col-sm-6">
                                    <div class="media-grid">
                                        <div class="img-wrapper" data-toggle="modal" data-target=".modal-1_@image.Id">
                                            <img src="~/images/Gallery/@image.ImagePath" alt="" class="img-responsive post-image" />
                                        </div>
                                        <div class="media-info">
                                            <div class="reaction">
                                                <a class="btn text-green" method="post" onclick="sendVote(@image.Id, true)"><div class="icon ion-thumbsup" id="upVotes_@image.Id">@image.UpVotes</div></a>
                                                <a class="btn text-red" method="post" onclick="sendVote(@image.Id, false)"><div class="fa fa-thumbs-down" id="downVotes_@image.Id">@image.DownVotes</div></a>
                                            </div>
                                        </div>
                                        <!--Popup-->
                                        <div class="modal fade modal-1_@image.Id" tabindex="-1" role="dialog" aria-hidden="true">
                                            <div class="modal-dialog modal-lg">
                                                <div class="modal-content">
                                                    <div class="post-content">
                                                        <img src="~/images/Gallery/@image.ImagePath" alt="post-image" class="img-responsive post-image" />
                                                        <div class="post-container">
                                                            <div class="post-detail">
                                                                <div class="user-info">
                                                                    <h5><a href="/Timeline/PersonalTimeLine?timelineId=@image.UserTimeLineId" class="profile-link">Uploaded by: @image.UserWhoUploaded</a></h5>
                                                                </div>
                                                                <div class="line-divider"></div>
                                                            </div>
                                                        </div>
                                                    </div>
                                                </div>
                                            </div>
                                        </div><!--Popup End-->
                                    </div>
                                </div>
                            }
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <!-- Scripts
    ================================================= -->
    <script async defer src="https://maps.googleapis.com/maps/api/js?key=AIzaSyCTMXfmDn0VlqWIyoOxK8997L-amWbUPiQ&callback=initMap"></script>
    <script src="~/js/jquery-3.1.1.min.js"></script>
    <script src="~/js/bootstrap.min.js"></script>
    <script src="~/js/jquery.sticky-kit.min.js"></script>
    <script src="~/js/jquery.scrollbar.min.js"></script>
    <script src="~/js/script.js"></script>
    <script src="~/js/jquery.form.js"></script>
</body>

@section Scripts{
    <script>
        function sendVote(imageId, isUpVote) {
            var json = { imageId: imageId, isUpVote: isUpVote };
            $.ajax({
                url: "/api/GalleryVote",
                type: "POST",
                data: JSON.stringify(json),
                contentType: "application/json; charset=utf-8",
                dataType: "json",
                success: function (data) {
                    $("#upVotes_" + imageId).html(data.upVotes);
                    $("#downVotes_" + imageId).html(data.downVotes);
                }
            });
        }
    </script>
}